rosnode kill /realsense/realsense2_camera
rosnode kill /realsense/realsense2_camera_manager
rosnode kill /realsense_secondary/realsense2_camera
rosnode kill /realsense_secondary/realsense2_camera_manager
